### ISSUE TITLE
Link Repo to Heroku

### ISSUE THREAD

**Issue by laylar** [Eazy-Sneezy/SocialMediaEazySneezy#10]
Set up heroku to automatically deploy this app every time we push to the deployment branch.

**Comment by logicbyjoel** [comment]
![image](https://user-images.githubusercontent.com/26174649/116798567-865ddc00-aab6-11eb-9e46-f3fb1e0ce271.png)

**Comment by logicbyjoel** [comment]
The linking of this repo to Heroku was successful.
